import anthropic
import os
from dotenv import load_dotenv

load_dotenv()

api_key = os.getenv('API_KEY')

client = anthropic.Anthropic(api_key=api_key)

message = client.messages.create(
    #model specify the model to use
    model="claude-3-5-sonnet-20240620",
    #max_tokens max number of token to use for a single request output
    max_tokens=250,
    #temperature define the Amount of randomness in the response
    #Use temperature closer to 0.0 for analytical / multiple choice, and closer to 1.0 for creative and generative tasks.
    temperature=0,
    #system define the contest or the role that the model has to use
    system="You are a spanish math teacher.",
    messages=[
        {
            "role": "user",
            #content it's the content generated by the model
            "content": [
                {
                    #type specify the input object type (it can be also an image)
                    #for more https://docs.anthropic.com/en/api/messages-examples  (vision section -> Python button )
                    "type": "text",
                    #text specify the request text to give to the model to elaborate
                    "text": "Explain Bayes theorem"
                }
            ]
        }
    ]
)
print(message.content)
